In [1]:
import numpy as np
import pandas as pd
import datetime

In [2]:
brand=pd.read_csv("train_brand.csv")
category=pd.read_csv("train_category.csv")
company=pd.read_csv("train_company.csv")

In [3]:
consumer=pd.read_csv("consumer_total.csv")
train_History=pd.read_csv("trainHistory.csv")

In [4]:
offers=pd.read_csv("offers.csv")

In [5]:
offers.head()

     offer  category  quantity    company  offervalue  brand
0  1190530      9115         1  108500080        5.00  93904
1  1194044      9909         1  107127979        1.00   6732
2  1197502      3203         1  106414464        0.75  13474
3  1198271      5558         1  107120272        1.50   5072
4  1198272      5558         1  107120272        1.50   5072

In [6]:
train_History[train_History.id==1000714152]

               id  chain    offer  market  repeattrips repeater   offerdate
81550  1000714152     46  1199258      15            1        t  2013-03-15

In [7]:
train_offer=train_History.merge(offers,on='offer')
train_offer.head()

,id,chain,offer,market,repeattrips,repeater,offerdate,category,quantity,company,offervalue,brand
0,86246,205,1208251,34,5,t,2013-04-24,2202,1,104460040,2.0,3718
1,15753725,17,1208251,4,0,f,2013-04-24,2202,1,104460040,2.0,3718
2,16535563,4,1208251,1,7,t,2013-04-27,2202,1,104460040,2.0,3718
3,18259179,3,1208251,2,0,f,2013-04-24,2202,1,104460040,2.0,3718
4,21024070,15,1208251,9,1,t,2013-04-23,2202,1,104460040,2.0,3718

In [8]:
trainconsumer=consumer.merge(train_offer,on="id")
trainconsumer.head()

,id,total_amount,total_quantity,total_trips,diffcompany,diffcategory,diffbrand,chain,offer,market,repeattrips,repeater,offerdate,category,quantity,company,offervalue,brand
0,100051423,2771.429977,807,85,190,192,228,4,1197502,1,0,f,2013-03-26,3203,1,106414464,0.75,13474
1,100084808,2790.199984,907,74,221,213,249,20,1197502,7,0,f,2013-03-26,3203,1,106414464,0.75,13474
2,100172712,7690.499942,3349,222,320,317,381,95,1200581,39,0,f,2013-03-30,1726,1,104460040,1.25,7668
3,100200838,3880.729944,1001,61,192,170,222,17,1208251,4,0,f,2013-04-24,2202,1,104460040,2.00,3718
4,1002116097,4158.509984,1612,61,206,228,266,46,1197502,15,1,t,2013-03-30,3203,1,106414464,0.75,13474

In [9]:
def diff_days(s1,s2):
    date_format = "%Y/%m/%d"
    a = datetime.datetime.strptime(s1, date_format)
    b = datetime.datetime.strptime(s2, date_format)
    delta = b - a
    return delta.days

In [10]:
def diff_offdays(s1,s2):
    a = datetime.datetime.strptime(s1, "%Y/%m/%d")
    b = datetime.datetime.strptime(s2, "%Y-%m-%d")
    delta = b - a
    return delta.days

In [11]:
consumer_brand=pd.DataFrame()
consumer_brand['id']=brand.id.unique()
consumer_category=pd.DataFrame()
consumer_category['id']=category.id.unique()
consumer_company=pd.DataFrame()
consumer_company['id']=company.id.unique()

In [12]:
#bybrand
def extrafeature(x,table):
    print('start-',x)
    if x=='brand':
        varx=brand
    elif x =='category':
        varx=category
    else:
        varx=company
    unique_id=varx.id.unique()
    for i in range(len(unique_id)):
        selectdata=varx[varx['id']== unique_id[i]].reset_index()
        offerday=trainconsumer.loc[trainconsumer.id ==selectdata.id[0],'offerdate'].values[0] 
        table.loc[i,'id']=unique_id[i]
        table.loc[i,x]=selectdata.loc[0,x]
        times=selectdata.shape[0]
        table.loc[i,'purchasetimes_'+x]=times
        table.loc[i,'total_amount_'+x]=selectdata['amount'].sum()
        table.loc[i,'total_quantit_'+x]=selectdata['quantity'].sum()
        table.loc[i,'purchaseperiod_'+x]=0
        table.loc[i,x+'period']=0
        table.loc[i,'before_30day_time_'+x]=0
        table.loc[i,'before_30day_quan_'+x]=0
        table.loc[i,'before_30day_amount_'+x]=0
        table.loc[i,'before_60day_time_'+x]=0
        table.loc[i,'before_60day_quan_'+x]=0
        table.loc[i,'before_60day_amount_'+x]=0
        table.loc[i,'before_90day_time_'+x]=0
        table.loc[i,'before_90day_quan_'+x]=0
        table.loc[i,'before_90day_amount_'+x]=0
        table.loc[i,'before_180day_time_'+x]=0
        table.loc[i,'before_180day_quan_'+x]=0
        table.loc[i,'before_180day_amount_'+x]=0
     
        
        if times >1:
            sumday=0
            period=0
            for k in range(1,times):
                offergap=diff_offdays(selectdata.loc[k,'date'],offerday)
                timegap=diff_days(selectdata.loc[k-1,'date'],selectdata.loc[k,'date'])
                sumday=sumday+int(timegap)
                period=period+(int(timegap)/(selectdata.loc[k-1,'quantity']))
                if  0 < offergap < 30:
                    table.loc[i,'before_30day_time_'+x]+= 1.0
                    table.loc[i,'before_30day_quan_'+x]+= float(selectdata.loc[k,'quantity'])
                    table.loc[i,'before_30day_amount_'+x]+= float(selectdata.loc[k,'amount'])
                        
                if 0 < offergap < 60:
                    table.loc[i,'before_60day_time_'+x]+= 1.0
                    table.loc[i,'before_60day_quan_'+x]+= float(selectdata.loc[k,'quantity'])
                    table.loc[i,'before_60day_amount_'+x]+= float(selectdata.loc[k,'amount'])
                        
                if  0 < offergap < 90:
                    table.loc[i,'before_90day_time_'+x]+= 1.0
                    table.loc[i,'before_90day_quan_'+x]+= float(selectdata.loc[k,'quantity'])
                    table.loc[i,'before_90day_amount_'+x]+= float(selectdata.loc[k,'amount'])
                        
                if 0 <  offergap < 180:
                    table.loc[i,'before_180day_time_'+x]+= 1.0
                    table.loc[i,'before_180day_quan_'+x]+= float(selectdata.loc[k,'quantity'])
                    table.loc[i,'before_180day_amount_'+x]+= float(selectdata.loc[k,'amount'])
                           
            if type(sumday)==int and sumday>0:    
                table.loc[i,'purchaseperiod_'+x]=(sumday/(times-1))
            if type(period)==int and period>0:
                table.loc[i,x+'period']=(period/(times-1))
        if i%10000==0:
            print(x+": "+ str(i)+"/"+str(len(unique_id)))

In [13]:
extrafeature('brand',consumer_brand)
extrafeature('company',consumer_company)
extrafeature('category',consumer_category)

start- brand
brand: 0/63151

/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:43: RuntimeWarning: divide by zero encountered in long_scalars

brand: 10000/63151
brand: 20000/63151
brand: 30000/63151
brand: 40000/63151
brand: 50000/63151
brand: 60000/63151
start- company
company: 0/86741
company: 10000/86741
company: 20000/86741
company: 30000/86741
company: 40000/86741
company: 50000/86741
company: 60000/86741
company: 70000/86741
company: 80000/86741
start- category
category: 0/87541
category: 10000/87541
category: 20000/87541
category: 30000/87541
category: 40000/87541
category: 50000/87541
category: 60000/87541
category: 70000/87541
category: 80000/87541

In [14]:
consumer_brand.to_csv("consumer_brand.csv")
consumer_company.to_csv("consumer_company.csv")
consumer_category.to_csv("consumer_category.csv")

In [16]:
##測試是否計算正確
unique_id=brand.id.unique()

selectdata=brand.loc[brand['id']== unique_id[898],].reset_index()
sumday=0
period=0
times=selectdata.shape[0]
if times==1:
    print('only once')
else:   
    for k in range(1,times):
        day1=datetime.datetime.strptime(selectdata['date'][k],'%Y/%m/%d')
        day2=datetime.datetime.strptime(selectdata['date'][k-1],'%Y/%m/%d')
        sumday=sumday+int((day1-day2).days)
        period=period+(int((day1-day2).days))/selectdata['quantity'][k-1]
    print("test:",sumday/(times-1))
print("loop:",consumer_brand.loc[898,'purchaseperiod_brand'])

test: 52.0
loop: 52.0

In [17]:
consumer_brand.head()

,id,brand,purchasetimes_brand,total_amount_brand,total_quantit_brand,purchaseperiod_brand,brandperiod,before_30day_time_brand,before_30day_quan_brand,before_30day_amount_brand,before_60day_time_brand,before_60day_quan_brand,before_60day_amount_brand,before_90day_time_brand,before_90day_quan_brand,before_90day_amount_brand,before_180day_time_brand,before_180day_quan_brand,before_180day_amount_brand
0,100007447,3718.0,1.0,2.69,1.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.00,0.0,0.0,0.00
1,100053952,102504.0,7.0,23.03,7.0,57.666667,0.0,0.0,0.0,0.0,1.0,1.0,3.99,2.0,2.0,7.98,3.0,3.0,10.98
2,1000714152,13791.0,9.0,29.72,12.0,37.000000,0.0,0.0,0.0,0.0,1.0,1.0,2.50,2.0,2.0,6.79,5.0,6.0,17.28
3,100245416,3718.0,3.0,8.07,3.0,125.000000,0.0,0.0,0.0,0.0,1.0,1.0,2.69,1.0,1.0,2.69,2.0,2.0,5.38
4,100258679,3718.0,1.0,3.49,1.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.00,0.0,0.0,0.00

In [20]:
##consumer_category測試是否計算正確
unique_id=category.id.unique()
selectdata=category.loc[category['id']== unique_id[919],].reset_index()
sumday=0
period=0
times=selectdata.shape[0]
if times==1:
    print('only once')
else:   
    for k in range(1,times):
        day1=datetime.datetime.strptime(selectdata['date'][k],'%Y/%m/%d')
        day2=datetime.datetime.strptime(selectdata['date'][k-1],'%Y/%m/%d')
        sumday=sumday+int((day1-day2).days)
        period=period+(int((day1-day2).days))/selectdata['quantity'][k-1]
    print("test:",sumday/(times-1))
print("loop:",consumer_category.loc[919,'purchaseperiod_category'])

test: 329.0
loop: 329.0

In [22]:
##consumer_company 測試是否計算正確
unique_id=company.id.unique()
selectdata=company.loc[company['id']== unique_id[55455],].reset_index()
sumday=0
period=0
times=selectdata.shape[0]
if times==1:
    print('only once')
else:   
    for k in range(1,times):
        day1=datetime.datetime.strptime(selectdata['date'][k],'%Y/%m/%d')
        day2=datetime.datetime.strptime(selectdata['date'][k-1],'%Y/%m/%d')
        sumday=sumday+int((day1-day2).days)
        period=period+(int((day1-day2).days))/selectdata['quantity'][k-1]
    print("test:",sumday/(times-1))
print("loop:",consumer_company.loc[55455,'purchaseperiod_company'])

only once
loop: 0.0

In [23]:
ccom=consumer_company.set_index('id')

In [24]:
ccate=consumer_category.set_index('id')

In [25]:
cbrand=consumer_brand.set_index('id')

In [27]:
cbrand.head()

,brand,purchasetimes_brand,total_amount_brand,total_quantit_brand,purchaseperiod_brand,brandperiod,before_30day_time_brand,before_30day_quan_brand,before_30day_amount_brand,before_60day_time_brand,before_60day_quan_brand,before_60day_amount_brand,before_90day_time_brand,before_90day_quan_brand,before_90day_amount_brand,before_180day_time_brand,before_180day_quan_brand,before_180day_amount_brand
id,,,,,,,,,,,,,,,,,,
100007447,3718.0,1.0,2.69,1.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.00,0.0,0.0,0.00
100053952,102504.0,7.0,23.03,7.0,57.666667,0.0,0.0,0.0,0.0,1.0,1.0,3.99,2.0,2.0,7.98,3.0,3.0,10.98
1000714152,13791.0,9.0,29.72,12.0,37.000000,0.0,0.0,0.0,0.0,1.0,1.0,2.50,2.0,2.0,6.79,5.0,6.0,17.28
100245416,3718.0,3.0,8.07,3.0,125.000000,0.0,0.0,0.0,0.0,1.0,1.0,2.69,1.0,1.0,2.69,2.0,2.0,5.38
100258679,3718.0,1.0,3.49,1.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.00,0.0,0.0,0.00

In [28]:
cc=ccom.join(ccate)
cc=cc.join(cbrand)
cc=cc.fillna(0)

In [41]:
cc[cc.before_90day_amount_company !=0].head()

,company,purchasetimes_company,total_amount_company,total_quantit_company,purchaseperiod_company,companyperiod,before_30day_time_company,before_30day_quan_company,before_30day_amount_company,before_60day_time_company,...,before_30day_amount_brand,before_60day_time_brand,before_60day_quan_brand,before_60day_amount_brand,before_90day_time_brand,before_90day_quan_brand,before_90day_amount_brand,before_180day_time_brand,before_180day_quan_brand,before_180day_amount_brand
id,,,,,,,,,,,,,,,,,,,,,
100007447,104460040.0,8.0,47.310000,9.0,52.000000,0.0,0.0,0.0,0.00,1.0,...,0.0,0.0,0.0,0.00,0.0,0.0,0.00,0.0,0.0,0.00
100033247,104460040.0,13.0,71.509999,15.0,28.000000,0.0,0.0,0.0,0.00,1.0,...,0.0,0.0,0.0,0.00,0.0,0.0,0.00,0.0,0.0,0.00
100053952,107717272.0,7.0,23.030000,7.0,57.666667,0.0,0.0,0.0,0.00,1.0,...,0.0,1.0,1.0,3.99,2.0,2.0,7.98,3.0,3.0,10.98
1000714152,105100050.0,28.0,102.169999,85.0,13.518519,0.0,5.0,16.0,12.43,9.0,...,0.0,1.0,1.0,2.50,2.0,2.0,6.79,5.0,6.0,17.28
100172712,104460040.0,11.0,34.160000,13.0,30.700000,0.0,0.0,0.0,0.00,2.0,...,0.0,0.0,0.0,0.00,0.0,0.0,0.00,0.0,0.0,0.00

In [47]:
traindata=trainconsumer.join(cc,rsuffix="_firstpurchase",on="id").fillna(0)

In [48]:
traindata[traindata['before_30day_amount_brand']!=0]

,id,total_amount,total_quantity,total_trips,diffcompany,diffcategory,diffbrand,chain,offer,market,...,before_30day_amount_brand,before_60day_time_brand,before_60day_quan_brand,before_60day_amount_brand,before_90day_time_brand,before_90day_quan_brand,before_90day_amount_brand,before_180day_time_brand,before_180day_quan_brand,before_180day_amount_brand
8,100444554,16818.919860,2580,100,438,294,522,15,1208251,9,...,8.670000,2.0,3.0,8.670000,2.0,3.0,8.670000,2.0,3.0,8.670000
10,1005207774,4451.569972,1567,31,291,261,288,46,1204576,15,...,5.000000,2.0,4.0,9.490000,3.0,6.0,14.490000,5.0,10.0,24.490000
19,1017618004,4041.609976,1517,90,226,240,267,46,1199256,15,...,12.180000,5.0,6.0,19.660000,8.0,11.0,36.620000,14.0,23.0,72.820000
50,103104842,2674.949965,717,102,217,180,235,15,1204576,9,...,5.760000,1.0,2.0,5.760000,1.0,2.0,5.760000,1.0,2.0,5.760000
58,103394300,6546.649936,1245,110,240,263,316,14,1208251,8,...,8.480000,1.0,2.0,8.480000,1.0,2.0,8.480000,1.0,2.0,8.480000
83,104480050,3144.589971,1133,62,168,156,185,15,1204822,9,...,3.000000,1.0,1.0,3.000000,1.0,1.0,3.000000,1.0,1.0,3.000000
91,104884542,4015.199940,1361,132,206,170,227,4,1204576,1,...,3.000000,2.0,2.0,6.990000,4.0,4.0,12.370000,4.0,4.0,12.370000
116,1059512826,1298.389991,892,22,117,102,108,46,1199258,15,...,2.000000,2.0,2.0,4.000000,2.0,2.0,4.000000,4.0,4.0,9.000000
124,106508086,3956.949965,1302,58,268,235,304,4,1204576,1,...,3.000000,1.0,1.0,3.000000,2.0,2.0,7.490000,3.0,3.0,10.480000
154,1080588152,6383.510012,2140,156,282,288,322,214,1208329,8,...,19.850000,4.0,7.0,26.520000,7.0,12.0,45.520000,7.0,12.0,45.520000
168,1087741597,4872.120012,1810,51,248,249,303,214,1198274,8,...,3.560000,5.0,5.0,9.100000,7.0,7.0,15.060000,12.0,15.0,32.180001
171,1089064406,4533.669984,2434,64,255,223,260,46,1199258,15,...,5.580000,3.0,3.0,8.070000,3.0,3.0,8.070000,5.0,5.0,13.240000
177,1092763135,6997.519958,2091,98,280,220,291,46,1208251,15,...,3.500000,1.0,1.0,3.500000,1.0,1.0,3.500000,4.0,6.0,19.260000
182,1099241449,9100.299958,3419,71,369,349,412,46,1199258,15,...,5.000000,3.0,4.0,10.000000,5.0,6.0,15.490000,9.0,10.0,28.260000
187,1102277292,6994.670013,2518,84,388,350,438,214,1198274,8,...,1.380000,1.0,1.0,1.380000,1.0,1.0,1.380000,6.0,7.0,9.640000
199,1118272117,3517.089986,1285,77,246,242,270,46,1199258,15,...,4.000000,2.0,3.0,7.080000,2.0,3.0,7.080000,2.0,3.0,7.080000
220,115025785,2274.779980,785,25,103,114,119,18,1204821,11,...,17.959999,3.0,5.0,22.449999,5.0,7.0,31.429998,9.0,17.0,75.829998
226,1154863741,13565.729990,5906,58,349,305,398,214,1208252,8,...,17.610000,5.0,8.0,28.110000,5.0,8.0,28.110000,11.0,18.0,61.070000
252,117114807,9288.469925,2609,97,339,295,404,14,1204576,8,...,6.990000,1.0,1.0,6.990000,1.0,1.0,6.990000,2.0,2.0,12.980000
256,1183658166,419.619997,289,27,135,118,112,46,1199258,15,...,2.500000,1.0,1.0,2.500000,1.0,1.0,2.500000,1.0,1.0,2.500000
265,1195551685,2683.789994,1172,47,190,192,205,46,1204576,15,...,7.980000,2.0,2.0,7.980000,2.0,2.0,7.980000,3.0,3.0,10.480000
271,1199287453,2425.290000,788,64,191,185,193,214,1208251,8,...,3.540000,1.0,1.0,3.540000,1.0,1.0,3.540000,3.0,4.0,13.030000
280,1204294383,11937.589950,3661,80,378,347,444,46,1199258,15,...,21.550000,7.0,12.0,43.570000,7.0,12.0,43.570000,13.0,18.0,61.789999
292,120967768,5671.139980,1882,228,304,302,387,18,1204576,11,...,7.980000,2.0,3.0,7.980000,3.0,4.0,11.970000,4.0,5.0,14.960000
309,121180302,16937.349860,4776,205,356,369,468,4,1204576,1,...,9.480000,3.0,5.0,17.360000,6.0,9.0,33.320000,6.0,9.0,33.320000
313,121254130,7112.689938,1957,130,340,315,397,88,1208251,14,...,4.390000,1.0,1.0,4.390000,2.0,2.0,6.880000,2.0,2.0,6.880000
323,121449855,13124.769890,4079,173,382,349,478,4,1208251,1,...,7.190000,1.0,1.0,7.190000,1.0,1.0,7.190000,1.0,1.0,7.190000
329,121534423,6921.299912,1897,69,269,259,306,14,1208251,8,...,5.000000,2.0,3.0,10.290000,3.0,5.0,16.570000,6.0,9.0,32.030000
332,121579528,4226.559970,1214,141,229,238,269,4,1204576,1,...,2.440000,2.0,2.0,6.430000,2.0,2.0,6.430000,3.0,3.0,9.930000
341,121753858,10627.880080,1884,180,269,267,331,3,1208251,2,...,2.290000,3.0,4.0,10.660000,5.0,6.0,15.840000,8.0,9.0,23.510000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
159775,764099524,4542.609990,2109,30,241,261,300,143,1208252,34,...,3.990000,2.0,2.0,6.170000,2.0,2.0,6.170000,2.0,2.0,6.170000
159776,764104206,12074.099920,3714,226,240,257,288,98,1208329,8,...,9.980000,3.0,3.0,14.969999,3.0,3.0,14.969999,3.0,3.0,14.969999
159780,764525080,2244.479992,1062,66,121,183,140,58,1208251,28,...,2.180000,1.0,1.0,2.180000,1.0,1.0,2.180000,2.0,2.0,4.360000
159818,768771466,3414.989987,1604,148,205,261,276,126,1208329,18,...,3.000000,1.0,1.0,3.000000,1.0,1.0,3.000000,1.0,1.0,3.000000
159819,768776978,4230.489982,1735,88,187,237,229,211,1208329,24,...,4.000000,2.0,2.0,7.340000,3.0,3.0,10.340000,3.0,3.0,10.340000
159830,769528055,7384.289972,2583,129,208,248,284,98,1208329,8,...,34.330000,9.0,24.0,91.330000,9.0,24.0,91.330000,9.0,24.0,91.330000
159831,769563092,4779.459970,1783,74,225,250,274,98,1208329,8,...,4.990000,3.0,4.0,15.980000,3.0,4.0,15.980000,3.0,4.0,15.980000
159836,769769207,8483.179947,2720,139,245,190,257,26,1204822,16,...,5.980000,1.0,2.0,5.980000,2.0,3.0,9.170000,2.0,3.0,9.170000
159847,770919682,1782.589992,1343,162,105,135,110,431,1204821,35,...,2.990000,1.0,1.0,2.990000,1.0,1.0,2.990000,1.0,1.0,2.990000
159853,771817576,6661.319974,2459,85,200,235,239,143,1208251,34,...,2.180000,2.0,2.0,4.360000,4.0,5.0,10.520000,6.0,9.0,19.240000
159855,771998549,3448.269989,1346,107,161,204,208,151,1208329,35,...,32.000000,2.0,8.0,32.000000,3.0,9.0,36.990000,4.0,13.0,49.990000
159856,772008054,5496.069948,2139,167,297,225,319,191,1208251,39,...,2.180000,2.0,2.0,5.470000,2.0,2.0,5.470000,4.0,4.0,10.940000
159859,772113318,2855.889984,1063,67,192,182,218,126,1208329,18,...,9.980000,3.0,3.0,14.969999,4.0,4.0,19.959999,4.0,4.0,19.959999
159879,78811334,10222.519900,3148,239,398,370,476,15,1204576,9,...,8.680000,4.0,4.0,15.660000,4.0,4.0,15.660000,5.0,5.0,19.650000
159881,792118268,3359.710008,1469,41,182,186,199,214,1208252,8,...,7.440000,2.0,2.0,7.440000,2.0,2.0,7.440000,2.0,2.0,7.440000
159898,823889199,5065.299975,2349,57,339,312,395,46,1199258,15,...,3.990000,3.0,3.0,8.980000,3.0,3.0,8.980000,4.0,4.0,10.860000
159907,839178874,4367.779967,1434,96,256,239,275,48,1204576,9,...,3.990000,3.0,3.0,11.970000,3.0,3.0,11.970000,3.0,3.0,11.970000
159927,86246,52828.119810,17333,381,954,599,1319,205,1208251,34,...,4.590000,5.0,5.0,14.950000,6.0,6.0,20.640000,7.0,7.0,23.130000
159928,86252,53592.899840,17604,368,898,590,1241,205,1197502,34,...,1.990000,1.0,1.0,1.990000,1.0,1.0,1.990000,1.0,1.0,1.990000
159938,863998171,6667.390002,2540,140,331,312,377,214,1198275,8,...,3.900000,3.0,4.0,9.460000,6.0,7.0,15.310000,11.0,12.0,25.060000
159951,868289277,5456.169991,2790,116,115,154,138,214,1208251,8,...,1.980000,1.0,1.0,1.980000,1.0,1.0,1.980000,1.0,1.0,1.980000
159952,868291178,3310.669981,1018,132,243,260,295,122,1208251,43,...,6.290000,1.0,1.0,6.290000,1.0,1.0,6.290000,1.0,1.0,6.290000
159965,872509949,10371.119940,2555,89,245,169,272,48,1198272,9,...,3.500000,1.0,1.0,3.500000,1.0,1.0,3.500000,4.0,4.0,12.070000
159968,873059112,6042.499993,1885,156,393,268,379,214,1208251,8,...,4.630000,1.0,1.0,4.630000,1.0,1.0,4.630000,2.0,2.0,9.260000
159969,873370502,8091.689984,3454,73,338,344,381,214,1208251,8,...,1.840000,1.0,2.0,1.840000,1.0,2.0,1.840000,3.0,4.0,7.380000
159971,873548964,3839.289996,1465,67,126,106,128,214,1208251,8,...,9.480000,1.0,1.0,9.480000,1.0,1.0,9.480000,1.0,1.0,9.480000
159988,881136698,5056.980005,2255,173,323,285,328,214,1208251,8,...,4.140000,1.0,1.0,4.140000,1.0,1.0,4.140000,2.0,2.0,6.120000
160000,885517176,1480.990000,720,122,101,144,105,214,1200988,8,...,6.910000,4.0,4.0,16.790000,6.0,6.0,20.740000,10.0,10.0,40.500000
160015,91550080,2719.979975,739,120,183,157,194,15,1204822,9,...,3.990000,1.0,1.0,3.990000,1.0,1.0,3.990000,1.0,1.0,3.990000
160037,97974482,1461.159988,615,71,81,90,89,18,1208251,11,...,2.690000,1.0,1.0,2.690000,1.0,1.0,2.690000,3.0,4.0,-0.110000

In [50]:
traindata.shape

(160059, 72)

In [51]:
traindata.columns

Index(['id', 'total_amount', 'total_quantity', 'total_trips', 'diffcompany',
       'diffcategory', 'diffbrand', 'chain', 'offer', 'market', 'repeattrips',
       'repeater', 'offerdate', 'category', 'quantity', 'company',
       'offervalue', 'brand', 'company_firstpurchase', 'purchasetimes_company',
       'total_amount_company', 'total_quantit_company',
       'purchaseperiod_company', 'companyperiod', 'before_30day_time_company',
       'before_30day_quan_company', 'before_30day_amount_company',
       'before_60day_time_company', 'before_60day_quan_company',
       'before_60day_amount_company', 'before_90day_time_company',
       'before_90day_quan_company', 'before_90day_amount_company',
       'before_180day_time_company', 'before_180day_quan_company',
       'before_180day_amount_company', 'category_firstpurchase',
       'purchasetimes_category', 'total_amount_category',
       'total_quantit_category', 'purchaseperiod_category', 'categoryperiod',
       'before_30day_time_category', 'before_30day_quan_category',
       'before_30day_amount_category', 'before_60day_time_category',
       'before_60day_quan_category', 'before_60day_amount_category',
       'before_90day_time_category', 'before_90day_quan_category',
       'before_90day_amount_category', 'before_180day_time_category',
       'before_180day_quan_category', 'before_180day_amount_category',
       'brand_firstpurchase', 'purchasetimes_brand', 'total_amount_brand',
       'total_quantit_brand', 'purchaseperiod_brand', 'brandperiod',
       'before_30day_time_brand', 'before_30day_quan_brand',
       'before_30day_amount_brand', 'before_60day_time_brand',
       'before_60day_quan_brand', 'before_60day_amount_brand',
       'before_90day_time_brand', 'before_90day_quan_brand',
       'before_90day_amount_brand', 'before_180day_time_brand',
       'before_180day_quan_brand', 'before_180day_amount_brand'],
      dtype='object')

In [52]:
list=['category','brand','company']
for k in list:
    col=k+'_firstpurchase'
    for i in range(traindata.shape[0]):
        if traindata.loc[i,col]==0:
            traindata.loc[i,col]=1
        else:
            traindata.loc[i,col]=0

In [53]:
traindata.to_csv('sum_consmer.csv')

In [54]:
consumer=pd.read_csv('sum_consmer.csv')
consumer['repeater'] = 1 * (consumer['repeater'] == 't')

In [55]:
consumer.head()

,Unnamed: 0,id,total_amount,total_quantity,total_trips,diffcompany,diffcategory,diffbrand,chain,offer,...,before_30day_amount_brand,before_60day_time_brand,before_60day_quan_brand,before_60day_amount_brand,before_90day_time_brand,before_90day_quan_brand,before_90day_amount_brand,before_180day_time_brand,before_180day_quan_brand,before_180day_amount_brand
0,0,100051423,2771.429977,807,85,190,192,228,4,1197502,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,1,100084808,2790.199984,907,74,221,213,249,20,1197502,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,2,100172712,7690.499942,3349,222,320,317,381,95,1200581,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,3,100200838,3880.729944,1001,61,192,170,222,17,1208251,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,4,1002116097,4158.509984,1612,61,206,228,266,46,1197502,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [58]:
#consumer=consumer.drop(columns=['Unnamed: 0'])
consumer.shape

(160059, 72)

In [62]:
for i in range(consumer.shape[0]):
    if consumer.loc[i,'total_amount_company']>1000 or consumer.loc[i,'total_amount_company']<0:
        consumer.loc[i,'total_amount_company']=consumer['total_amount_company'].mean()
for i in range(consumer.shape[0]):
    if consumer.loc[i,'total_quantit_company']>1000 or consumer.loc[i,'total_quantit_company']<0:
        consumer.loc[i,'total_quantit_company']=consumer['total_quantit_company'].mean()
for i in range(consumer.shape[0]):
    if consumer.loc[i,'total_amount_category']>1000 or consumer.loc[i,'total_amount_category']<0:
        consumer.loc[i,'total_amount_category']=consumer['total_amount_category'].mean()
for i in range(consumer.shape[0]):
    if consumer.loc[i,'total_quantit_category']>1000 or consumer.loc[i,'total_quantit_category']<0:
        consumer.loc[i,'total_quantit_category']=consumer['total_quantit_category'].mean()   
for i in range(consumer.shape[0]):
    if consumer.loc[i,'total_amount_brand']>1000 or consumer.loc[i,'total_amount_brand']<0:
        consumer.loc[i,'total_amount_brand']=consumer['total_amount_brand'].mean()
for i in range(consumer.shape[0]):
    if consumer.loc[i,'total_quantit_brand']>1000 or consumer.loc[i,'total_quantit_brand']<0:
        consumer.loc[i,'total_quantit_brand']=consumer['total_quantit_brand'].mean()
for i in range(consumer.shape[0]):
    if consumer.loc[i,'total_amount']>10000 or consumer.loc[i,'total_amount']<0:
        consumer.loc[i,'total_amount']=consumer['total_amount'].mean()
for i in range(consumer.shape[0]):
    if consumer.loc[i,'total_quantity']>10000 or consumer.loc[i,'total_quantity']<0:
        consumer.loc[i,'total_quantity']=consumer['total_quantity'].mean()
for i in range(consumer.shape[0]):
    if consumer.loc[i,'categoryperiod']<0 :
        consumer.loc[i,'categoryperiod']=0
for i in range(consumer.shape[0]):
    if consumer.loc[i,'brandperiod']<0:
        consumer.loc[i,'brandperiod']=0
for i in range(consumer.shape[0]):
    if consumer.loc[i,'companyperiod']<0:
        consumer.loc[i,'companyperiod']=0   
for i in range(consumer.shape[0]):
    if consumer.loc[i,'purchaseperiod_brand']<=0:
        consumer.loc[i,'purchaseperiod_brand']=consumer['purchaseperiod_brand'].mean()
for i in range(consumer.shape[0]):
    if consumer.loc[i,'purchaseperiod_company']<=0:
        consumer.loc[i,'purchaseperiod_company']=consumer['purchaseperiod_company'].mean()
for i in range(consumer.shape[0]):
    if consumer.loc[i,'purchaseperiod_category']<=0:
        consumer.loc[i,'purchaseperiod_category']=consumer['purchaseperiod_category'].mean()

In [65]:
consumer['ave_spend']=consumer['total_amount']/consumer['total_trips']
consumer['ave_quant']=consumer['total_quantity']/consumer['total_trips']
consumer['ave_unique_company_bought']=consumer['diffcompany']/consumer['total_trips']
consumer['ave_unique_category_bought']=consumer['diffcategory']/consumer['total_trips']
consumer['ave_unique_brand_bought']=consumer['diffbrand']/consumer['total_trips']

In [68]:
consumer[consumer.before_180day_amount_brand!=0].head()

,id,total_amount,total_quantity,total_trips,diffcompany,diffcategory,diffbrand,chain,offer,market,...,before_90day_quan_brand,before_90day_amount_brand,before_180day_time_brand,before_180day_quan_brand,before_180day_amount_brand,ave_spend,ave_quant,ave_unique_company_bought,ave_unique_category_bought,ave_unique_brand_bought
8,100444554,5673.575517,2580.0,100,438,294,522,15,1208251,9,...,3.0,8.67,2.0,3.0,8.67,56.735755,25.800000,4.380000,2.940000,5.220000
10,1005207774,4451.569972,1567.0,31,291,261,288,46,1204576,15,...,6.0,14.49,5.0,10.0,24.49,143.599031,50.548387,9.387097,8.419355,9.290323
19,1017618004,4041.609976,1517.0,90,226,240,267,46,1199256,15,...,11.0,36.62,14.0,23.0,72.82,44.906778,16.855556,2.511111,2.666667,2.966667
24,101961875,3397.119954,926.0,67,173,169,187,15,1208251,9,...,2.0,4.68,1.0,2.0,4.68,50.703283,13.820896,2.582090,2.522388,2.791045
26,1021253705,1061.249991,344.0,18,116,114,119,46,1199256,15,...,0.0,0.00,2.0,2.0,5.87,58.958333,19.111111,6.444444,6.333333,6.611111

In [70]:
consumer.drop_duplicates()
consumer.shape

(160059, 77)

In [71]:
consumer.to_csv('sum_consmer.csv')